### ISSUE TITLE
夏老师您好，我在跑您们代码时候遇到点问题

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [NUSTM/SHARK#2]
您们requirements.txt里第一行写的是certifi @ file:///croot/certifi_1665076670883/work/certifi

我在运行"pip install -r requirements.txt"安装的时候，报错ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/croot/certifi_1665076670883/work/certifi'

是因为我的电脑上没有这个路径

有啥办法能解决吗

**Comment by ffcarina** [comment]
@qwertyuiopasdfghjklzxcn 抱歉，requirements.txt文件是我从跑实验的镜像里直接导出的，这个问题我暂时也不知道是为什么。其实我们实验所用环境和[BART-ABSA](https://github.com/yhcc/BARTABSA)一样，您可以尝试安装一下transformers和fastnlp。

**Comment by ffcarina** [comment]
@qwertyuiopasdfghjklzxcn  您好，我已经更新了requirements.txt，删掉第一行应该就没问题了。

**Comment by qwertyuiopasdfghjklzxcn** [comment]
谢谢同学，我这边还是报错
你那边是否方便采用docker镜像技术，把您的项目打包为镜像文件分享给我
感谢！

**Comment by ffcarina** [comment]
@qwertyuiopasdfghjklzxcn  请问报错是否是`ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cu113`？如果是这样，加一行`-f https://download.pytorch.org/whl/cu113/torch_stable.html`指定PyTorch 的源即可，`requirements.txt`已更新。
